global:
  scrape_interval:     10s
  evaluation_interval: 10s


rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ '172.16.100.245:9093' ]

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator-inventory'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.100.245:8082']

  - job_name: 'spring-actuator-order'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.16.100.245:8080' ]

  - job_name: 'spring-actuator-payment'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.16.100.245:8088' ]

  - job_name: 'windows-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.16.100.245:9182' ]

  - job_name: 'rabbitmq-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.16.100.245:15692' ]