spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/order-db
    username: postgres
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

server:
  port: 8080

---


queue:
  order-create: ORDER_CREATED_EVENT
  order-done: ORDER_DONE_EVENT
  order-canceled: ORDER_CANCELED_EVENT
  reset-inventory: RESET_INVENTORY_EVENT

exchange:
  order-exchange: ORDER_EXCHANGE
#  order-cancel-exchange: ORDER_CANCEL_EXCHANGE

routingKey:
  order-create-key: ORDER_CREATE_KEY
  order-done-key: ORDER_DONE_KEY
  order-canceled-key: ORDER_CANCELED_KEY
  reset-inventory-key: RESET_INVENTORY_KEY


management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

